image: deeson/default-pipeline:latest

clone:
  depth: full

pipelines:
  default:
    - step:
        script:
          - ENVIRONMENT=pipelines make test

  branches:
    master:
      - step:
          script:
            - ENVIRONMENT=pipelines make test
            - ENVIRONMENT=pipelines make deploy-stage
    develop:
      - step:
          script:
            - ENVIRONMENT=pipelines make test
            - ENVIRONMENT=pipelines make deploy-test
  tags:
    '*':
      - step:
          script:
            - ENVIRONMENT=pipelines make test
            - ENVIRONMENT=pipelines make deploy-prod
