image: phpunit/phpunit:5.0.3

# We need the full commit history for deployment.
clone:
  depth: full

pipelines:
  default:
    - step:
        script:
          - make test
          - make deploy RUN_DESTRUCTIVE=true
